Runtime Interface Reflection: rmw_implementation
ros2/rosidl_dynamic_typesupport_fastrtps pull request #1
Opened 2023-03-08 22:17 UTC by methylDragon

This PR is part of the runtime interface reflection subscription feature of REP-2011: https://github.com/ros2/ros2/issues/1374

# Description
This PR provisions a serialization support library implementation fulfilling the interface laid out in `rosidl_dynamic_typesupport`

2023-04-07 22:13 UTC, wjwwood requested changes
This generally lgtm, I removed a lot of my staged comments as they revolved around either:

- print functions, which we've agreed to remove before merging, and
- how double-pointers and allocations in the functions are used a lot when it's not necessary, which we've agreed to fix in follow up pr's if there's time

So I will approve this with the print functions removed.

2023-04-07 23:35 UTC, methylDragon commented
> This generally lgtm, I removed a lot of my staged comments as they revolved around either:
> 
> * print functions, which we've agreed to remove before merging, and
> * how double-pointers and allocations in the functions are used a lot when it's not necessary, which we've agreed to fix in follow up pr's if there's time
> 
> So I will approve this with the print functions removed.

https://github.com/ros2/rosidl_dynamic_typesupport_fastrtps/pull/1/commits/0f5ae5abde1c6010cce77c8fe18b51bc13b9c17f

Print functions removed :grimacing:

2023-04-08 09:11 UTC, wjwwood approved these changes

2023-04-08 09:11 UTC, wjwwood commented on src/serialization_support.cpp
> +    new rosidl_dynamic_typesupport_serialization_support_interface_t();
We discussed this too, that it should be a static variable and returned as `const *`. But this would be in the allocation refactor follow up.

2023-04-08 18:58 UTC, merged